DROP SCHEMA IF EXISTS online_apteka;

CREATE SCHEMA IF NOT EXISTS online_apteka
CHARACTER SET utf8;

USE online_apteka;

CREATE TABLE Role (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ROLE_NAME VARCHAR(255) NOT NULL
  
);

CREATE TABLE User (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  SECOND_NAME VARCHAR(255) NOT NULL,
  FK_ROLE_ID INTEGER NOT NULL,
	CONSTRAINT FK_ROLE FOREIGN KEY (FK_ROLE_ID) REFERENCES Role (ID)
	ON DELETE cascade
    ON UPDATE cascade
);

CREATE TABLE User_locale (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  SECOND_NAME VARCHAR(255) NOT NULL,
  FK_ROLE_ID INTEGER NOT NULL,
	CONSTRAINT FK_ROLE FOREIGN KEY (FK_ROLE_ID) REFERENCES Role (ID)
	ON DELETE cascade
    ON UPDATE cascade
);

CREATE TABLE Category (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CATEGORY_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE Category_locale (
  ID_Category INTEGER NOT NULL,
  	CONSTRAINT ID_Category FOREIGN KEY (ID_Category) REFERENCES Category (ID)
	ON DELETE cascade
    ON UPDATE cascade,
  LOCALE VARCHAR(50) NOT NULL,
  CATEGORY_NAME VARCHAR(255) NOT NULL
);


CREATE TABLE Drug (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DRUGNAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(755) NOT NULL,
  DOSAGE VARCHAR(50) NOT NULL,
  INSTRUCTION VARCHAR(1000) NOT NULL,
  PRICE DECIMAL(6,2) NOT NULL,
  QUANTITY FLOAT NOT NULL,
  NEED_RECIPE BOOLEAN NOT NULL,
  IMAGE_PATH VARCHAR(255) NOT NULL,
  FK_CATEGORY_ID INTEGER NOT NULL,
	CONSTRAINT FK_CATEGORY FOREIGN KEY (FK_CATEGORY_ID) REFERENCES Category (ID)
	ON DELETE cascade
    ON UPDATE cascade
);

CREATE TABLE Drug_locale (
  ID_DRUG INTEGER NOT NULL,
  	CONSTRAINT ID_DRUG FOREIGN KEY (ID_DRUG) REFERENCES Drug (ID)
	ON DELETE cascade
    ON UPDATE cascade,
  LOCALE VARCHAR(50) NOT NULL,
  DRUGNAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(755) NOT NULL,
  DOSAGE VARCHAR(50) NOT NULL,
  INSTRUCTION VARCHAR(1000) NOT NULL
);

CREATE TABLE Recipe (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DOCTOR_NAME VARCHAR(255) NOT NULL,
  BEGIN_DATE Date NOT NULL,
  END_DATE Date NOT NULL,
  FK_USER_TO_RECIPE INTEGER NOT NULL,
	CONSTRAINT FK_USER_TO_RECIPE FOREIGN KEY (FK_USER_TO_RECIPE) REFERENCES User (ID)
	ON DELETE cascade
    ON UPDATE cascade

);

CREATE TABLE RecipeDetail (
  DOSAGE VARCHAR(255) NOT NULL,
  QUANTITY FLOAT NOT NULL,
  FK_DRUG_TO_RECIPE INTEGER NOT NULL,
	CONSTRAINT FK_DRUG_TO_RECIPE FOREIGN KEY (FK_DRUG_TO_RECIPE) REFERENCES Drug (ID)
	ON DELETE cascade
    ON UPDATE cascade,
  FK_Recipe_ID INTEGER NOT NULL,
	CONSTRAINT FK_Recipe FOREIGN KEY (FK_Recipe_ID) REFERENCES Recipe (ID)
	ON DELETE cascade
    ON UPDATE cascade
);

CREATE TABLE Cart (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  QUANTITY FLOAT NOT NULL,
  FK_DRUG_TO_CART INTEGER NOT NULL,
	CONSTRAINT FK_DRUG FOREIGN KEY (FK_DRUG_TO_CART) REFERENCES Drug (ID)
	ON DELETE cascade
    ON UPDATE cascade,
  FK_USER_TO_CART INTEGER NOT NULL,
	CONSTRAINT FK_USER FOREIGN KEY (FK_USER_TO_CART) REFERENCES User (ID)
	ON DELETE cascade
    ON UPDATE cascade
);

CREATE TABLE CustomOrder (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ORDER_DATE Datetime NOT NULL,
  TOTALPRICE DECIMAL(6,2) NOT NULL,
  ORDER_STATUS INTEGER NOT NULL,
  FK_USER_TO_ORDER INTEGER NOT NULL,
	CONSTRAINT FK_USER_TO_ORDER FOREIGN KEY (FK_USER_TO_ORDER) REFERENCES User (ID)
	ON DELETE cascade
    ON UPDATE cascade
);

CREATE TABLE OrderDetail (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  QUANTITY INTEGER NOT NULL,
  TOTALPRICE DECIMAL(6,2) NOT NULL,
  FK_DRUG_TO_ORDER INTEGER NOT NULL,
	CONSTRAINT FK_DRUG_TO_ORDER FOREIGN KEY (FK_DRUG_TO_ORDER) REFERENCES Drug (ID)
	ON DELETE cascade
    ON UPDATE cascade,
  FK_CUSTOMORDER_ID INTEGER NOT NULL,
	CONSTRAINT FK_CUSTOMORDER FOREIGN KEY (FK_CUSTOMORDER_ID) REFERENCES CustomOrder (ID)
	ON DELETE cascade
    ON UPDATE cascade
);